# generated by datamodel-codegen:
#   filename:  Chunk.json

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Field, constr


class Chunk(BaseModel):
    text: constr(min_length=1) = Field(..., description='Contenu textuel du chunk.')
    metadata: Optional[
        Dict[str, Union[str, bool, int, List[Union[str, bool, int]]]]
    ] = Field({}, description='Métadonnées du chunk.')
