# generated by datamodel-codegen:
#   filename:  IndexingStageConfiguration.json

from __future__ import annotations

from pydantic import BaseModel, Field


class IndexingStageConfiguration(BaseModel):
    collection_name: str = Field(
        ...,
        description='Nom de la collection dans laquelle les documents sont enregistrés.',
    )
    database_uri: str = Field(..., description='URI de la base PG Vector')
    openai_embedding_model: str = Field(..., description='Nom du modèle OpenAI utilisé')
