# generated by datamodel-codegen:
#   filename:  IngestionWorkflowInput.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .IndexingStageConfiguration import IndexingStageConfiguration
from .Source import Source


class IngestionWorkflowInput(BaseModel):
    sources: List[Source] = Field(..., description="Liste des pages web d'entrée")
    indexing_config: Optional[IndexingStageConfiguration] = None
