# generated by datamodel-codegen:
#   filename:  MimeTypesEnum.json

from __future__ import annotations

from enum import Enum


class MimeTypesEnum(str, Enum):
    application_epub_zip = 'application/epub+zip'
    application_json = 'application/json'
    application_pdf = 'application/pdf'
    application_rtf = 'application/rtf'
    application_vnd_ms_excel = 'application/vnd.ms-excel'
    application_vnd_tock_ingestion_folder = 'application/vnd.tock-ingestion.folder'
    application_vnd_google_apps_document = 'application/vnd.google-apps.document'
    application_vnd_google_apps_drawing = 'application/vnd.google-apps.drawing'
    application_vnd_google_apps_folder = 'application/vnd.google-apps.folder'
    application_vnd_google_apps_form = 'application/vnd.google-apps.form'
    application_vnd_google_apps_presentation = (
        'application/vnd.google-apps.presentation'
    )
    application_vnd_google_apps_script = 'application/vnd.google-apps.script'
    application_vnd_google_apps_site = 'application/vnd.google-apps.site'
    application_vnd_google_apps_shortcut = 'application/vnd.google-apps.shortcut'
    application_vnd_google_apps_spreadsheet = 'application/vnd.google-apps.spreadsheet'
    application_vnd_oasis_opendocument_presentation = (
        'application/vnd.oasis.opendocument.presentation'
    )
    application_vnd_oasis_opendocument_spreadsheet = (
        'application/vnd.oasis.opendocument.spreadsheet'
    )
    application_vnd_oasis_opendocument_text = 'application/vnd.oasis.opendocument.text'
    application_vnd_openxmlformats_officedocument_presentationml_presentation = (
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    )
    application_vnd_openxmlformats_officedocument_spreadsheetml_sheet = (
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    application_vnd_openxmlformats_officedocument_wordprocessingml_document = (
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    image_bmp = 'image/bmp'
    image_gif = 'image/gif'
    image_jp2 = 'image/jp2'
    image_jpeg = 'image/jpeg'
    image_jpm = 'image/jpm'
    image_png = 'image/png'
    image_tiff = 'image/tiff'
    image_webp = 'image/webp'
    image_x_portable_anymap = 'image/x-portable-anymap'
    text_csv = 'text/csv'
    text_html = 'text/html'
    text_markdown = 'text/markdown'
    text_plain = 'text/plain'
    text_tab_separated_values = 'text/tab-separated-values'
