# generated by datamodel-codegen:
#   filename:  RecursiveChunkingStageConfiguration.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class RecursiveChunkingStageConfiguration(BaseModel):
    chunk_size: Optional[int] = Field(
        None, description='Taille des chunk en caractères.'
    )
    chunk_overlap: Optional[int] = Field(
        None, description='Taille des chunk en caractères.'
    )
