# generated by datamodel-codegen:
#   filename:  SourceOptions.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class SourceOptions(BaseModel):
    crawling_url_startswith: Optional[List[constr(min_length=7)]] = Field(
        None, description='Restraint les URLs crawlées a démarrer avec ce prefix.'
    )
