# generated by datamodel-codegen:
#   filename:  Source.json

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Field, constr

from .MimeTypesEnum import MimeTypesEnum
from .SourceOptions import SourceOptions
from .SourceStatusEnum import SourceStatusEnum
from .StageEnum import StageEnum


class Source(BaseModel):
    uri: constr(min_length=7) = Field(..., description='Source URI, URL de la page web')
    mime_type: Optional[MimeTypesEnum] = None
    max_depth: Optional[int] = Field(
        0, description='Maximum depth to crawl for this source'
    )
    error: Optional[str] = None
    raw_file_path: Optional[str] = Field(
        None, description='Raw source file path, HTML scraped pages.'
    )
    converted_md_path: Optional[str] = Field(
        None,
        description='Chemin vers le fichier MD issue de la conversion de la page web.',
    )
    chunking_file_path: Optional[str] = Field(
        None, description='Path to the chunking output yaml file.'
    )
    parent_uri: Optional[str] = Field(None, description='URL de la page parent.')
    current_stage: Optional[StageEnum] = None
    current_status: Optional[SourceStatusEnum] = None
    options: Optional[SourceOptions] = None
    metadata: Optional[
        Dict[str, Union[str, bool, int, List[Union[str, bool, int]]]]
    ] = Field(None, description='Metadata of the source')
