# generated by datamodel-codegen:
#   filename:  SourceStatusEnum.json

from __future__ import annotations

from enum import Enum


class SourceStatusEnum(str, Enum):
    DISCOVERED = 'DISCOVERED'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    ERROR = 'ERROR'
