# generated by datamodel-codegen:
#   filename:  StageEnum.json

from __future__ import annotations

from enum import Enum


class StageEnum(str, Enum):
    CRAWLING = 'CRAWLING'
    SCRAPING = 'SCRAPING'
    CONVERTION = 'CONVERTION'
    CHUNKING = 'CHUNKING'
    INDEXING = 'INDEXING'
