/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload d'entrée du workflow
 */
export interface IngestionWorkflowInput {
  /**
   * Liste des pages web d'entrée
   */
  sources: Source[];
  indexing_config?: IndexingStageConfiguration;
}
/**
 * Chaque page web est une source.
 */
export interface Source {
  /**
   * Source URI, URL de la page web
   */
  uri: string;
  mime_type?: MimeTypesEnum;
  /**
   * Maximum depth to crawl for this source
   */
  max_depth?: number;
  error?: string;
  /**
   * Raw source file path, HTML scraped pages.
   */
  raw_file_path?: string;
  /**
   * Chemin vers le fichier MD issue de la conversion de la page web.
   */
  converted_md_path?: string;
  /**
   * Path to the chunking output yaml file.
   */
  chunking_file_path?: string;
  /**
   * URL de la page parent.
   */
  parent_uri?: string;
  current_stage?: StageEnum;
  /**
   * Metadata of the source
   */
  metadata?: {
    [k: string]: string | boolean | number | (string | boolean | number)[];
  };
}
/**
 * Configration de stage d'embedding / vectorisation.
 */
export interface IndexingStageConfiguration {
  /**
   * Nom de la collection dans laquelle les documents sont enregistrés.
   */
  collection_name: string;
  /**
   * URI de la base PG Vector
   */
  database_uri: string;
  /**
   * Nom du modèle OpenAI utilisé
   */
  openai_embedding_model: string;
}

/**
 * Source mime type
 */
export enum MimeTypesEnum {
  "application/epub+zip" = "application/epub+zip",
  "application/json" = "application/json",
  "application/pdf" = "application/pdf",
  "application/rtf" = "application/rtf",
  "application/vnd.ms-excel" = "application/vnd.ms-excel",
  "application/vnd.tock-ingestion.folder" = "application/vnd.tock-ingestion.folder",
  "application/vnd.google-apps.document" = "application/vnd.google-apps.document",
  "application/vnd.google-apps.drawing" = "application/vnd.google-apps.drawing",
  "application/vnd.google-apps.folder" = "application/vnd.google-apps.folder",
  "application/vnd.google-apps.form" = "application/vnd.google-apps.form",
  "application/vnd.google-apps.presentation" = "application/vnd.google-apps.presentation",
  "application/vnd.google-apps.script" = "application/vnd.google-apps.script",
  "application/vnd.google-apps.site" = "application/vnd.google-apps.site",
  "application/vnd.google-apps.shortcut" = "application/vnd.google-apps.shortcut",
  "application/vnd.google-apps.spreadsheet" = "application/vnd.google-apps.spreadsheet",
  "application/vnd.oasis.opendocument.presentation" = "application/vnd.oasis.opendocument.presentation",
  "application/vnd.oasis.opendocument.spreadsheet" = "application/vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.text" = "application/vnd.oasis.opendocument.text",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation" = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "image/bmp" = "image/bmp",
  "image/gif" = "image/gif",
  "image/jp2" = "image/jp2",
  "image/jpeg" = "image/jpeg",
  "image/jpm" = "image/jpm",
  "image/png" = "image/png",
  "image/tiff" = "image/tiff",
  "image/webp" = "image/webp",
  "image/x-portable-anymap" = "image/x-portable-anymap",
  "text/csv" = "text/csv",
  "text/html" = "text/html",
  "text/markdown" = "text/markdown",
  "text/plain" = "text/plain",
  "text/tab-separated-values" = "text/tab-separated-values"
}
/**
 * Liste des stage existant dans le workflow.
 */
export enum StageEnum {
  CRAWLING = "CRAWLING",
  SCRAPING = "SCRAPING",
  CONVERTION = "CONVERTION",
  CHUNKING = "CHUNKING",
  INDEXING = "INDEXING"
}
